### ISSUE TITLE
object data some digit does not mask

### ISSUE THREAD

**Issue by addikhann** [Sumukha1496/maskdata#10]
I used you service it's really great . but i'm facing one issue... when i pass object....   unmaskedStartDigits: 4,   unmaskedEndDigits: 1  not working  check below
const maskJSONOptions = {
  
    maskWith: "*",  
    unmaskedStartDigits: 4,    
    unmaskedEndDigits: 4,
    fields: ['CARDNUMBER', 'CardNumber','cardNumber','CC_NUMBER'] ,
   
  };
var obj = { cardNumber: "123456789123" ,abc: "abceew" ,efg: 121212" }
 var result=  MaskData.maskJSONFields(obj, maskJSONOptions)
result  { cardNumber: "****************" ,abc: "abceew" ,efg: 121212" },

if want like this   { cardNumber: "1234******9123" ,abc: "abceew" ,efg: 121212" },

**Comment by Sumukha1496** [comment]
@addikhann , Thank you for rasing the issue. I am working on it and will update you as soon as possible.

**Comment by Sumukha1496** [comment]
@addikhann , 
Masking Json fields doesn't have options like unmaskedStartDigits, unmaskedEndDigits. 
In your case, one of the fields is the card number and you want to mask it. 
So, the approach is, 
`
const MaskData = require('./maskdata');
 
const maskCardOptions = {
  maskWith: "*",
  unmaskedStartDigits: 4, 
  unmaskedEndDigits: 4
};

let obj = { cardNumber: "123456789123" ,abc: "abceew" ,efg: "121212" } ;
obj['cardNumber'] = MaskData.maskCard(obj['cardNumber'], maskCardOptions);
console.log(obj);
`
Then the output will be `{ cardNumber: "1234******9123" ,abc: "abceew" ,efg: 121212" }`

**Comment by Sumukha1496** [comment]
Another approach would be, 

``` const maskCardOptions = {
  maskWith: "*",
  unmaskedStartDigits: 4, 
  unmaskedEndDigits: 4
};

const obj = { cardNumber: "123456789123" ,abc: "abceew" ,efg: "121212" } ;
const result = MaskData.replaceValue(obj, 'cardNumber', MaskData.maskCard(obj['cardNumber'], maskCardOptions));
```

Then the output will be { cardNumber: "1234******9123" ,abc: "abceew" ,efg: 121212" }

**Comment by Sumukha1496** [comment]
Closing this issue

**Comment by addikhann** [comment]
thanks for your response.
but i have different fields on runtime i want to mask.. like cardNumber, CC_Number , DD_Number and soo on.. i want to mask not only card number.  
fields: ['CARDNUMBER', 'CardNumber','cardNumber','CC_NUMBER'] ,

**Comment by Sumukha1496** [comment]
got it. You want partial masking of json fields. 
I will consider this and come up with a new version including partial masking.
