### ISSUE TITLE
Request: Ability to custom set masking options

### ISSUE THREAD

**Issue by ericlau-solid** [Sumukha1496/maskdata#11]
This library seems great so far. The only thing I would like to add is ability to custom set masking option, like masking all values with * but the last X chars (show those).

**Comment by Sumukha1496** [comment]
Hi @ericlau-solid , For which masking you want this option? The feature you are talking about is already there. 
there is a configuration parameter "maskWith". With the help of this option, you can change the to "X" or other characters.

If you can tell me the exact use case, I can give the sample configuration.

**Comment by Sumukha1496** [comment]
Send me the use case, How you are using it currently with the dummy code. I can send you the corresponding documentation and a way to do it. In case the feature is not available, I can include it in the next version.

**Comment by Sumukha1496** [comment]
@ericlau-solid , Got it.
You want to mask all values and show only last X characters. 

But which function you are using? There are mask string, card, password, email, phone, etc... functions.

**Comment by ericlau-solid** [comment]
@Sumukha1496 api keys, passwords. There are plenty of things like api keys that are secret, but we need to show the last XXXX characters so devs can compare and reasonably conclude whether key X or Y was recorded.

**Comment by Sumukha1496** [comment]
@ericlau-solid, Got it. Let me think about it. I will add this in this next version. You can expect the new version before the end of this week.

**Comment by Sumukha1496** [comment]
This is WIP. Some more testing and load testing is pending. I will roll out the new version once they are completed

**Comment by Sumukha1496** [comment]
@ericlau-solid, If I am not wrong, what you were looking for is something like this: https://www.npmjs.com/package/maskdata#release-features 

Please check it and let me know

**Comment by Sumukha1496** [comment]
You can use the version: 1.1.3

**Comment by Sumukha1496** [comment]
Also, Please take a look into the configuration: "maxMaskedCharacters". 
Use --> Assume your secret key/password is a big string. When we mask it, it will become simply *********************.......

But if you don't want as many characters as in the input string and want to limit it, set maxMaskedCharacters to some valid value. You can check the documentation for more info and example

**Comment by Sumukha1496** [comment]
@ericlau-solid, Let me know once you check the new version. This helps in closing the issue ticket

**Comment by ericlau-solid** [comment]
@Sumukha1496 looks good. Consider it closed.

**Comment by Sumukha1496** [comment]
@ericlau-solid , Thanks for the verification

**Comment by Marufa-Mukadam** [comment]
how can i retrieve the original password for user login verification
