### ISSUE TITLE
Have you thought about writing this in TypeScript?

### ISSUE THREAD

**Issue by ujwal-setlur** [Sumukha1496/maskdata#13]
I like the look of this, but slightly challenging to incorporate this into my TypeScript project without liberal use of ``any`` or writing handcrafted ``index.d.ts``. With Typescript quite prevalent, have you thought about writing this in TypeScript?

**Comment by Sumukha1496** [comment]
Hi @ujwal-setlur , 
       Let me think about it. I will plan for the same

**Comment by Sumukha1496** [comment]
hi @ujwal-setlur , I am working on the typescript module. You can expect the fully tested module in 1 or 2 weeks.

**Comment by Sumukha1496** [comment]
@ujwal-setlur, Can you share your use case and which masking function you are trying to use?

**Comment by ujwal-setlur** [comment]
@Sumukha1496 I am interested in the maskJson() function. I actually implemented a typescript version of that code.

**Comment by Sumukha1496** [comment]
Got it. But What is stopping you from using the existing one? I didn't get the exact problem you are facing. Is it while providing the configs?

**Comment by ujwal-setlur** [comment]
I can use the existing ones, but I would have to write typings for the functions I would use. Doable of course, but since this is a relatively small library, and I needed just that one function, I just implemented in typescript.

**Comment by Sumukha1496** [comment]
@ujwal-setlur , Please check this: https://www.npmjs.com/package/maskdata#maskdata-for-typescript (Version: 1.2.2)

for the type definitions and typescript support. Let me know if you find any issues in using the library. Closing the ticket for now.

**Comment by ujwal-setlur** [comment]
Thanks, will take a look.
