### ISSUE TITLE
Masking complete string

### ISSUE THREAD

**Issue by AMARNATHRAO** [Sumukha1496/maskdata#15]
As we have "Mask the exact substring from throughout the string" in this module. I think it's better to have a function to mask the entire string with the masking parameters. As it is a common use-case in many places like if we want to mask "**user full name**" etc.
Now, we have to go for **Mask fields in a JSON** function, and again we have to do some manipulations according to the requirement.
I feel it is good to have some function to handle such conditions straight away, You can consider this if you feel the same.

**Comment by Sumukha1496** [comment]
Hi @AMARNATHRAO, Thank you for raising this issue. I feel its a valid and much needed usecase. I will add this feature in the next version. You can expect this to be done by 5th June 2021 EOD.

**Comment by Sumukha1496** [comment]
Hi @AMARNATHRAO , Please check version 1.1.6. 
https://www.npmjs.com/package/maskdata#release-features 

Let me know if this works fine. I will close the ticket.

**Comment by Sumukha1496** [comment]
more info is here: https://www.npmjs.com/package/maskdata#mask-the-characters-or-words-in-the-string

**Comment by AMARNATHRAO** [comment]
Hi, @Sumukha1496. It is working as you mentioned in the document. Thanks for the quick response, I feel if we have **unmaskedStartCharacters**, **unmaskedEndCharacters** these options in the masking string it would be more useful for the people who are using this which is much needed while we are masking. 
Example : Amar******* ****ke
where **unmaskedStartCharacters = 4** and **unmaskedEndCharacters = 2**

**Comment by Sumukha1496** [comment]
@AMARNATHRAO, Got it. I will work on it and push it in the next versions. 
Please raise more such issues, so that I can improve the library. Thank you.
