### ISSUE TITLE
unmaskedStartCharacters, unmaskedEndCharacters in mask String function

### ISSUE THREAD

**Issue by Sumukha1496** [Sumukha1496/maskdata#17]
unmaskedStartCharacters, unmaskedEndCharacters in mask String function

**Comment by pengxiangg** [comment]
Hi @Sumukha1496 thank you for providing this library. I saw that this issue has been closed but I'm not able to use the unmaskedStartCharacters and unmaskedEndCharacters options in the mask string function. Are the options not feasible for the mask string function? 

Thank you!

**Comment by Sumukha1496** [comment]
Hi @pengxiangg , Thank you for raising the issue. Can you please let me know your usecase so that I can plan for adding these parameters. For now, I will reopen this issue.

**Comment by Sumukha1496** [comment]
Why I am asking for the usecase is, If its similar to password masking, you already have the option to use maskPassword() with unmaskedStartCharacters, unmaskedEndCharacters. 
If it is not a password and you don;t want to mix your usecase with the password masking usecase, I can think about it and plan to release these features in the next version

**Comment by pengxiangg** [comment]
Hi @Sumukha1496 Thank you for your reply. My use case is for address. I originally used the mask string function to keep the spaces visible, but I realised that it did not have the unmaskedStartCharacters. I'm using the password masking now for unmaskedStartCharacters as keeping the spaces visible isn't that crucial for my use case.

**Comment by Sumukha1496** [comment]
@pengxiangg , Please check V1.3.0 --> https://www.npmjs.com/package/maskdata?activeTab=readme#json-mask-examples
With this you can extend your usecase to generic strings. If you need more configs here, let me know. Closing this issue for now.
