### ISSUE TITLE
Null checks in maskPhone function

### ISSUE THREAD

**Issue by AMARNATHRAO** [Sumukha1496/maskdata#19]
Hi @Sumukha1496 
I came across an issue when I am using the **maskPhone** function where null checks are not handled. I am using **"maskdata": "^1.1.4"** version. We can handle in application level by still I feel this should be done in the module itself. You can consider this as an issue if you feel the same.

**Comment by Sumukha1496** [comment]
@AMARNATHRAO , Let me check this

**Comment by Sumukha1496** [comment]
Hi @AMARNATHRAO , It is taken care in the version: 1.1.7
