### ISSUE TITLE
Not able to mask JSON Fields within Objects

### ISSUE THREAD

**Issue by dookieloserr** [Sumukha1496/maskdata#2]
If test object contains another Object within the JSON, is not able to mask one field of the embeeded JSON.
For Example
Given the fields array as:
fields : ['password', 'firstName','testObject.firstName'] 

Then:
testObject.firstName is Masked

    const obj = {
    password : "IKnowNothing",
    firstName : "Jon",
    lastName : "Snoww",
    testObject: {
        firstName:"test"
    }
    };

Failed output:
{
  password: '************',
  firstName: '***',
  lastName: 'Snoww',
  testObject: { firstName: 'test' }
}

**Comment by Sumukha1496** [comment]
@dookieloserr , Will check and resolve it asap.

**Comment by Sumukha1496** [comment]
Fixed the issue in https://github.com/Sumukha1496/maskdata/commit/c3f5542342e026b541b2a1bc765af5ee17b6d80f. (version 1.0.8 and above)
