### ISSUE TITLE
maxMaskedCharacters option for maskingJSON fields

### ISSUE THREAD

**Issue by matias53** [Sumukha1496/maskdata#21]
Hi this is a great tool, I've tested the option of masking some JSON fields and it works well, but the option to set the maxMaskedCharacters does not work for JSON fields. It only works for maskPassword.

Would you be so kind of adding that feature for the next versions?
Thx

**Comment by Sumukha1496** [comment]
Hi @matias53 , 
   Thank you for the input. I will think about it and work on it in the next version

**Comment by iuadastra** [comment]
Hi @Sumukha1496 , any updates on this? This feature would really help if you store PKI (looong strings) configuration in JSON

**Comment by Sumukha1496** [comment]
Hi @iuadastra , I am working on it. You can expect the fix in the next version by Next monday

**Comment by xxJoJoxx** [comment]
This is exactly what I'm looking for as well, really hoping to get it soon haha I was wondering why I didn't see the option in the docs

**Comment by Sumukha1496** [comment]
Hi @xxJoJoxx  , @iuadastra , Sorry for the delay. I am already done with the changes and push the next version after some testing. Hopefully by today EOD

**Comment by Sumukha1496** [comment]
@xxJoJoxx , @iuadastra @matias53 Please check the version: 1.1.10  or refer below link for the new feature

https://www.npmjs.com/package/maskdata#release-features

**Comment by Sumukha1496** [comment]
Only limitation is the type of value should be a string. then only this feature will be enabled.
