### ISSUE TITLE
Nest json unmaskedStartCharacters and unmaskedEndCharacters not working

### ISSUE THREAD

**Issue by ghost** [Sumukha1496/maskdata#27]

**Comment by Sumukha1496** [comment]
Hi @arunkleargroup , currently, this feature is not present for json masking. Can you please add your usecase and need for this feature along with an example?. I will check and try to add it in the next version

**Comment by arunkleargroup** [comment]
Thank you for you response. I am using https://logger.tsed.io , I am printing request and response , have to mask bank accountno first 4 digits.

**Comment by stocks29** [comment]
This would be a nice feature to have!

**Comment by Sumukha1496** [comment]
@stocks29 , @arunatoa , I am working on this. You can expect this in the next version

**Comment by RezaRahmati** [comment]
@Sumukha1496 we have same request too,

In our case we are going to store full api request and response , both request and response contains name, email, card number

Right now we are running masking multiple times with different rules to be able to mask all

It would have been great if mask json would have support group of configuration, each group can contains `fields` and rule which can be any of Password, Email, Phone, String, Card

This way with one round of maskJSONFields we can mask all data at once

**Comment by Sumukha1496** [comment]
@RezaRahmati , This work is in progress. Once the changes are published, I will inform you. 

Just a peek into the changes: 

With a single function call, you can mask card, email, phone, password, string fields in an object either with the default options or the custom options provided by the library for each type of fields.

**Comment by Sumukha1496** [comment]
@RezaRahmati , @stocks29 , please check the version: 1.2.0. If there is any issue or bugs, feel free to report.

**Comment by Sumukha1496** [comment]
https://www.npmjs.com/package/maskdata#release-features 

https://www.npmjs.com/package/maskdata#mask-json
