### ISSUE TITLE
How to preserve data type in maskWith

### ISSUE THREAD

**Issue by shahidmau** [Sumukha1496/maskdata#3]
Hi, how to preserve the datatype of the **maskWith** value. See the given example.

    const MaskData = require('maskdata');
    const maskNumbers = {
        maskWith: 9,
        fields: ['order_status']
    };
    let inputData = {
        order_status: 1
    }
    let output = MaskData.maskJSONFields(inputData, maskNumbers);

Output (it is converting integer to string)
`{order_status: '9'}`

Expected
`{order_status: 9}`

**Comment by Sumukha1496** [comment]
It is not possible as of now. You have to manually do it. (Like: inputData.order_status *= 1,  Number(inputData.order_status) etc.. ). 

But I am not able to find the use case with this. Usually people use X/x, * or other characters to mask. **Why replace a number with another number and call it masking**? Please explain it to me. If I find its good to have this feature, I can work on it and publish a new version.

**Comment by shahidmau** [comment]
It is useful in case we mask data and again insert into database, so any change in data type will throw the error while inserting into the database.

for example for any **pii** information: 

**input**
    {
    name: "John"
    age: 31
    }

**output**
    {
    name: "XXX"
    age: 99
    }

but if you change the datatype **Integer** value to **String** then it will given error while inserting back to the database.

**Comment by Sumukha1496** [comment]
Got it.. I will work on it to give a new property (preserveType). Will publish a new version soon.

**Comment by Sumukha1496** [comment]
I was thinking about this and I don't think this needs to be included in a masking library. If you are sure of the datatype, You can convert it to that type after using maskdata or use the `replaceValue` method to replace(As this is not masking) the value by keeping the data type.
