### ISSUE TITLE
Supporting nested arrays

### ISSUE THREAD

**Issue by davidbani** [Sumukha1496/maskdata#34]
I have been unable to mask nested arrays.

For example `Data[*].items[*].id` does not mask `id` in **every** `items` array: 

```
{
"Data": [
    {
      "id": "1111",
      "name": "Test",
      "items": [
        {
          "id": "1111",
          "name": "11115",
        },
        {
          "id": "1111",
          "name": "11111",
        }
      ],
      
    },
     {
      "id": "1111",
      "name": "Test",
      "items": [
        {
          "id": "1111",
          "name": "11115",
        },
        {
          "id": "1111",
          "name": "11111",
        }
      ],
    }
  ]
}
```
Items array is completely masked. Unless there is a workaround? 

Also is there a way for apply a mask to ALL related fields without having to traverse? E.g.  `fields: ['name']`

Will update ALL name fields: 
```
{
  "name": "****",
  "items": {
     "name": "****"
   }
}
```

**Comment by Sumukha1496** [comment]
Hi @davidbani , for the first issue, currently it supports only 1 *. So 1 iteration is needed. Iterate through data and for each data, you can mask items[*].id

Currently 2nd feature is not supported. But both features seems really cool and good to have. I will work on it and push these changes in the next version. I will keep you updated. Thanks for raising the issue.

**Comment by Sumukha1496** [comment]
Hi @davidbani , please check this: https://www.npmjs.com/package/maskdata?activeTab=readme#mask-multiple-fields and let me know if there are any issues

**Comment by Sumukha1496** [comment]
@davidbani , use version 1.2.4 instead of 1.2.3 as 1.2.4 comes with a minor bug fix
