### ISSUE TITLE
Unmask the data

### ISSUE THREAD

**Issue by Marufa-Mukadam** [Sumukha1496/maskdata#35]
I have masked the password data using maskdata library but i want to verify a user login , how can i unmask the data

**Comment by Sumukha1496** [comment]
@Marufa-Mukadam, This library masks a password and do not encrypt it. So, there is no way to retrieve the original password after masking it. If your usecase is securely storing the password and then do login verification, you need to encrypt the password and compare the hash to do login verification.

This library is mainly for logging, non-retrieve usecases. Hope this helps.
