### ISSUE TITLE
Printing half of the json content

### ISSUE THREAD

**Issue by pncabhisek3** [Sumukha1496/maskdata#39]
let arr = ['todos[0].todo.values[2]', 'todos[0].todo.values[1]'];
let logMasker = require('maskdata');
const jsonInput = {
    todos: [
        {
            todo: {
                name: 'tododddddd1',
                credit: '1234-5678-8765-1234',
                values: [11000122, 1092277, 3301299],
                labels: [{ name: 'l1' }]
            }
        }
    ]
};

for (let i = 0; i < arr.length; i++) {
    let partOpt = {
        passwordMaskOptions: {
            maskWith: "!",
            unmaskedStartCharacters: i+1,
            unmaskedEndCharacters: i+2
        },
        passwordFields: [''],
    }
    partOpt.passwordFields.pop();
    partOpt.passwordFields.push(arr[i]);
    console.log("part opt before: ", partOpt);
    let jsonInput2 = logMasker.maskJSON2(jsonInput, partOpt);
    console.log("output--}{}: ", i, jsonInput2);
}

**OUTPUT:**
part opt before:  {
  passwordMaskOptions: {
    maskWith: '!',
    unmaskedStartCharacters: 1,
    unmaskedEndCharacters: 2
  },
  passwordFields: [ 'todos[0].todo.values[2]' ]
}
output--}{}:  0 { todos: [ { todo: [Object] } ] }
part opt before:  {
  passwordMaskOptions: {
    maskWith: '!',
    unmaskedStartCharacters: 2,
    unmaskedEndCharacters: 3
  },
  passwordFields: [ 'todos[0].todo.values[1]' ]

**ISSUE:**  Not entire json is getting printed. You can clearly see the nested object is getting replaced by '[Object]'

**Comment by Sumukha1496** [comment]
Hi @pncabhisek3 , This is not the issue with this library. This is the default behaviour of console.log. It won't print the nested objects. To print the nested objects, you can either use `console.dir(jsonInput2, { depth: null }); ` OR, 
you can use JSON.stringify(). `console.log("output--}{}: ", i, JSON.stringify(jsonInput2));`

**Comment by Sumukha1496** [comment]
Hope this helps. There are other options to print the nested objects. You can check this: https://stackoverflow.com/questions/10729276/how-can-i-get-the-full-object-in-node-jss-console-log-rather-than-object
