### ISSUE TITLE
Supporting Masking of array or object values

### ISSUE THREAD

**Issue by shahidmau** [Sumukha1496/maskdata#4]
Is there any way to mask the given field in the array of json data.

`fields: ['order_status', 'orders[*].order_id', 'shipping.address', 'billing.*']`

**input**

    {
        order_status: 1,
        orders: [
            {
                order_id: 'A001',
                date: "10-10-2019"
            },
            {
                order_id: 'A002',
                date: "10-11-2019"
            }
        ],
        shipping: {
            address: "9th main, 6th cross, jp nagar"
        },
        billing: {
            name: "John",
            address: "10th floor, abc road."
        }
    }

**output**

    {
        "order_status": "XXXX",
        "orders": [
            {
                "order_id": "XXXX",
                "date": "10-10-2019"
            },
            {
                "order_id": "XXXX",
                "date": "10-11-2019"
            }
        ],
        "shipping": {
            "address": "XXXX"
        },
        "billing": {
            "name": "XXXX",
            "address": "XXXX"
        }
    }

**Comment by Sumukha1496** [comment]
Sample : https://www.npmjs.com/package/maskdata#mask-fields-of-a-nested-object

**Comment by shahidmau** [comment]
Hi, it is still working for these rules

** orders[*].order_id ** -> every **order_id** of the array **orders** (don't mask the other fields of the same array object, like **date** in the above example)

** billing.* ** -> every key of the object **billing**

** orders[*] ** -> every key of every object of the array

**Comment by Sumukha1496** [comment]
Please check v1.0.14
