### ISSUE TITLE
Feature Request: Generic Mask Option for JSON

### ISSUE THREAD

**Issue by pengxiangg** [Sumukha1496/maskdata#40]
I would like to mask multiple fields in JSON but these fields have different requirements for unmaskStart and unmaskEnd characters. However, there is currently only one function with this masking option (password). 

The feature request is to allow users to create more masking options (that is based on the password option) for different string fields.
Maybe something like 
```
const jsonMaskConfig = {
  otherOptions: [ 
      { 
           maskOptions: {maskWith: "X", unmaskedStartCharacters: 1, unmaskedEndCharacters: 1},
           fields: [firstName] 
      }, 
      { 
           maskOptions: {maskWith: "X", unmaskedStartCharacters: 2},
           fields: [lastName] 
      }
}
```

**Comment by Sumukha1496** [comment]
Hi @pengxiangg , This is a good to have feature. I will make this change in the upcoming version. Thank you

**Comment by Sumukha1496** [comment]
@pengxiangg , I am working on this change and you can expect it soon

**Comment by pengxiangg** [comment]
Hi @Sumukha1496 thank you so much for your hard work! Looking forward to this new feature. Hope you had a great vacation!

**Comment by Sumukha1496** [comment]
@pengxiangg , Please check V1.3.0 --> https://www.npmjs.com/package/maskdata?activeTab=readme#json-mask-examples
With this you can extend your usecase to generic strings. If you need more configs here, let me know. Closing this issue for now.
