### ISSUE TITLE
Does maskdata use regular expressions during masking process?

### ISSUE THREAD

**Issue by C3S4R5** [Sumukha1496/maskdata#41]
Thank you all for this grate work, I'm a little bit worry about the performance of masking several attributes on long JSONs, I have seen similar projects that use regular expressions in the replace/mask process, so, I would like to know if maskdata is using regular expressions.

**Comment by Sumukha1496** [comment]
Hi @C3S4R5 , I will check and get back to you on the issue...

**Comment by Sumukha1496** [comment]
Hi @C3S4R5, No this library doesn't make use of regex expect to validate the input UUID(Only in case of UUID masking). Since regex can affect the performance of the applications, I haven't used it.

**Comment by C3S4R5** [comment]
Thanks
