### ISSUE TITLE
Is there a way to extend the available kinds of masking?

### ISSUE THREAD

**Issue by C3S4R5** [Sumukha1496/maskdata#42]
Currently you have done an excellent work creating these: maskCard, maskEmail, maskPassword, maskPhone, maskString, maskUuid, maskJwt.
Is there a way I can implement a maskDriverLicense for example, to be used inside the maskJSON, taking you work as base?

**Comment by Sumukha1496** [comment]
Hi @C3S4R5 , I will check and get back to you on the issue...

**Comment by Sumukha1496** [comment]
Hi @C3S4R5 , Can you help me with the format / example of DriverLicense data? I can work on it and publish a new version

**Comment by C3S4R5** [comment]
Hi @Sumukha1496. I said driver license just as an example, actually, I think the feature described in this [https://github.com/Sumukha1496/maskdata/issues/40](url) issue could allow what I need. Inside the suggested "otherOptions" I could define N custom masking options to mask N attributes inside a JSON

**Comment by Sumukha1496** [comment]
Hi @C3S4R5 , Please check V1.3.0 --> https://www.npmjs.com/package/maskdata?activeTab=readme#json-mask-examples 
With this you can extend your usecase to generic strings. If you need more configs here, let me know. Closing this issue for now.
