### ISSUE TITLE
Feature Request: Support leading wildcard in JSON field

### ISSUE THREAD

**Issue by TanjaBayer** [Sumukha1496/maskdata#45]
What do you think about adding support for leading wildcards. E.g. *.password, which would then mask all values in all nested levels:
```json
{
"data":
   [
      {"password":"123"}
   ], 
"password":"555"
}
```

Both occurrences will be removed (and even more):

```
{
"data":
   [
      {"password":"***"}
   ], 
"password":"***"
}
```

Right now I use the following function for this:

```ts
export function maskValues<T extends object>(obj: T, keysToMask: string[]): T {

  function maskRecursively(item: any): any {
    if (Array.isArray(item)) {
      return item.map(maskRecursively);
    } else if (item !== null && typeof item === 'object') {
      const maskedObj: { [key: string]: string } = {};
      for (const key in item) {
        if (Object.prototype.hasOwnProperty.call(item, key)) {
          maskedObj[key] =
            keysToMask.includes(key) && typeof maskedObj[key] === 'string'
              ? MaskData.maskStringV2(maskedObj[key])
              : maskRecursively(item[key]);
        }
      }
      return maskedObj;
    }
    return item;
  }

  return maskRecursively(obj);
}
```

In my case I use all string inputs as only fields I am looking for, but the code could be adapted, that this kind of search would be only performed for keys starting with '*.' and splitting them for the '*.'.

**Comment by TanjaBayer** [comment]
Hi @Sumukha1496 thanks for the fast response, using `[*].` and/or `.*` notations does not help solve the issue. Because with this I can only mask all fields with a specific key in an array or any fields below a specific field. But in my case I only know the key, but not its position in the object.

Also I found that the way the data is copied in the maskJSON2 function https://github.com/Sumukha1496/maskdata/blob/5eeff736de384b5b421dd192106838b1506ffa9b/lib/maskService/JsonMask.js#L34 some data will be changed.   


If the obj is e.g a Buffer, the copied data is altered in a way, that it can not be used in a similar way as before, if you would use structuredClone the data would be still different, however it would be usable , see the example below

``` bash
> const a = Buffer.from([0xf])
undefined
> a
<Buffer 0f>
> JSON.parse(JSON.stringify(a))
{ type: 'Buffer', data: [ 15 ] }
> structuredClone(a)
Uint8Array(1) [ 15 ]

> a.subarray(0)
<Buffer 0f>
> structuredClone(a).subarray(0)
Uint8Array(1) [ 15 ]
> JSON.parse(JSON.stringify(a)).subarray(0)
Uncaught TypeError: JSON.parse(...).subarray is not a function
```

**Comment by Sumukha1496** [comment]
Got it. I will address these concerns in the next version. It can be a nice feature to have. Thank you for raising this issue.

**Comment by Sumukha1496** [comment]
You are right. But the issue with structuredClone is that it is not supported and older versions of the browsers and I don't want to this library to be a reason for breaking this. Most of the mask usecases are with simple data. So, it works fine with json.parse(json.stringify). 

But as you mentioned, structuredClone addresses the limitations with json.parse(json.stringify). So, I will definitely keep this task in the backlog and take it up in the future.

**Comment by Sumukha1496** [comment]
I am working on the recursive masking feature that you mentioned. I will release the new version within 2 days and let you know.

**Comment by Sumukha1496** [comment]
Hello @TanjaBayer , Please check this: https://www.npmjs.com/package/maskdata#release-features 
Hope this is what you were looking for

**Comment by TanjaBayer** [comment]
This looks good, thank you.

**Comment by Sumukha1496** [comment]
Thank you for raising the issue. It is a good to have feature.
