### ISSUE TITLE
MaskData.maskString options with maxMaskedCharacters

### ISSUE THREAD

**Issue by jp-904** [Sumukha1496/maskdata#49]
Just wondering if option: maxMaskedCharacters is available for maskString method.
I have a use case to mask Token in string 
Test case:

const privacyStrListForTest = ['password', 'eyJ0bmsiOiJjb3JlL3Byb2QvMDBEMGwwMDAwMDBFQ3hlRUFHIiwidmVyIjoiMS4wIiwia2lkIjoiQ09SRV9BVEpXVC4wMEQwbDAwMDAwMEVDeGUuMTcxMDIxNTc1MjkxMyIsInR0eSI6InNmZGMtY29yZS10b2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0']
const passwordForMask = 'password'
const tokenForMask = 'eyJ0bmsiOiJjb3JlL3Byb2QvMDBEMGwwMDAwMDBFQ3hlRUFHIiwidmVyIjoiMS4wIiwia2lkIjoiQ09SRV9BVEpXVC4wMEQwbDAwMDAwMEVDeGUuMTcxMDIxNTc1MjkxMyIsInR0eSI6InNmZGMtY29yZS10b2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0'
const myStr = `This PWD: ${passwordForMask} This TOKEN: ${tokenForMask} END`

const maskStringOptions = {
  maskWith: "*",
  values: privacyStrListForTest,
  maskOnlyFirstOccurance: false,
  maskAll: false,
  maskSpace: true
};

console.log(`Masking: ` + MaskData.maskString(myStr, maskStringOptions))

#########output##########
Masking: This PWD: ******** This TOKEN: ******************************************************************************************************************************************************************************************************* END

**Comment by Sumukha1496** [comment]
Hi @jp-904 , Please check these : 
1. https://www.npmjs.com/package/maskdata#generic-string-masking   --> This is the version2 of the mask string functionality. This has the maxMaskedCharacters and fixedOutputLength configs. 

2. https://www.npmjs.com/package/maskdata#mask-password --> Same configs are available here also. 

3. If you have jwt, then you can use this also --> https://www.npmjs.com/package/maskdata#mask-jwt-token

**Comment by Sumukha1496** [comment]
Also, if you have these inside a json and if you want to mask, you can make use of https://www.npmjs.com/package/maskdata#mask-json

**Comment by Sumukha1496** [comment]
<img width="856" alt="Screenshot 2024-08-05 at 4 37 45 PM" src="https://github.com/user-attachments/assets/471376d5-78f5-47cf-9703-ff09c1beba85">

```
const privacyStrListForTest = ['password', 'eyJ0bmsiOiJjb3JlL3Byb2QvMDBEMGwwMDAwMDBFQ3hlRUFHIiwidmVyIjoiMS4wIiwia2lkIjoiQ09SRV9BVEpXVC4wMEQwbDAwMDAwMEVDeGUuMTcxMDIxNTc1MjkxMyIsInR0eSI6InNmZGMtY29yZS10b2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0']

const stringMaskV2Options = {
  maskWith: "X",
  maxMaskedCharacters: 10, 
  unmaskedStartCharacters: 4,
  unmaskedEndCharacters: 9,
  fixedOutputLength: undefined
};

const jsonMask2Config = {
  genericStrings: [
    {
      config: { maskWith: "X", maxMaskedCharacters: 5},
      fields: ["0"]
    },
    {
      config: { maskWith: "*", maxMaskedCharacters: 20},
      fields: ["1"]
    }
  ]
}
console.log(MaskData.maskJSON2(privacyStrListForTest, jsonMask2Config));
```

**Comment by jp-904** [comment]
Thanks @Sumukha1496 , I am trying to handle both String and Json Object type. Json Object type works fine. Just in String type I want to use the values: property as I might have many fields to be masked. 

In this case, the last option you provided should work for me in this case. Many thanks

**Comment by jp-904** [comment]
Hi @Sumukha1496 I realized that the mask is not working for method maskString if the string contains $ symbol. If I have to use maskString method, is there a way to do it? Many thanks. I prefer to use maskString because it give me option to mask specific values by matching them in string.

**Comment by Sumukha1496** [comment]
Hi @jp-904 ,  Can you give the sample input?

**Comment by jp-904** [comment]
Thanks @Sumukha1496   

The order of $ doesn't matter. 

const privacyStrListForTest = ['p$assword', 'eyJ0bmsiOiJjb3JlL3Byb2QvMDBEMGwwMDAwMDBFQ3hlRUFHIiwidmVyIjoiMS4wIiwia2lkIjoiQ09SRV9BVEpXVC4wMEQwbDAwMDAwMEVDeGUuMTcxMDIxNTc1MjkxMyIsInR0eSI6InNmZGMtY29yZS10b2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0']
const passwordForMask = 'p$assword'
const tokenForMask = 'eyJ0bmsiOiJjb3JlL3Byb2QvMDBEMGwwMDAwMDBFQ3hlRUFHIiwidmVyIjoiMS4wIiwia2lkIjoiQ09SRV9BVEpXVC4wMEQwbDAwMDAwMEVDeGUuMTcxMDIxNTc1MjkxMyIsInR0eSI6InNmZGMtY29yZS10b2tlbiIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0'
const myStr = `This PWD: ${passwordForMask} This TOKEN: ${tokenForMask} END`

const maskStringOptions = {
maskWith: "*",
values: privacyStrListForTest,
maskOnlyFirstOccurance: false,
maskAll: false,
maskSpace: true
};

console.log(`Masking: `  + MaskData.maskString(myStr, maskStringOptions))

###Output###
Masking: This PWD: p$assword This TOKEN: ******************************************************************************************************************************************************************************************************* END

**Comment by Sumukha1496** [comment]
@jp-904 , got it. I will release a new version with this fix and also maxMaskedCharacters in the maskString functionality as you asked.

**Comment by Sumukha1496** [comment]
@jp-904 , you can install version 1.3.3. 

It works with strings having characters like $ & [ ] { } etc.... 

But with this version, maxMaskedCharacters is not supported. I will plan for it in the future.
