### ISSUE TITLE
'mask fields in a JSON' functionality masks original object; expected - return new masked object

### ISSUE THREAD

**Issue by romanowa** [Sumukha1496/maskdata#5]
Hi!
Thanks for the module!
But have one additional expectation from it. When i use masking for JSON - i expect to have masked object as a new object, in order to pass it to the logger, for example, and use original unmasked object further in my code.

**Comment by Sumukha1496** [comment]
Got it. It should have been the behaviour. Thanks for raising this issue. I am working on it. Will push the updates by EOD.

**Comment by Sumukha1496** [comment]
Fixed it. (v1.0.16). Please check it. If you find any issues, please raise it here.
